import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Navbar from "../app/src/components/navbar"; // @ belgisiga e'tibor bering
import Footer from "../app/src/components/footer";
import { ModalProvider } from "../app/context/ModalContext";
import CallbackModalWrapper from "../app/src/components/CallbackModalWrapper"; // Importni tekshiring
import Providers from "../store/providers";
import { ToastContainer } from 'react-toastify';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=DM+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" />

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col items-center">
        {/* Barcha providerlarni eng tepaga o'raymiz */}
        <ModalProvider>
          <Providers>
            <ToastContainer position="top-right" autoClose={2000} />
            <div className="w-full max-w-[1508px] mx-auto flex flex-col min-h-screen">
              <Navbar />
              <main className="flex-grow">
                {children}
              </main>
              {/* Modal har doim body ichida, lekin Footer bilan bir xil context ichida bo'lishi kerak */}
              <CallbackModalWrapper />
              <Footer />
            </div>
          </Providers>
        </ModalProvider>
      </body>
    </html>
  );
}
